2025-03-12 23:51:59,767 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-03-12 23:51:59,768 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Configure stats pid to 12193
2025-03-12 23:51:59,768 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Loading settings from /home/inae/.config/wandb/settings
2025-03-12 23:51:59,768 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Loading settings from /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/settings
2025-03-12 23:51:59,768 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'disabled': 'False'}
2025-03-12 23:51:59,769 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'jax_noisy/main_qas.py', 'program_abspath': '/mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/main_qas.py', 'program': '/mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/main_qas.py'}
2025-03-12 23:51:59,769 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-03-12 23:51:59,769 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2025-03-12 23:51:59,769 INFO    MainThread:12193 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-03-12 23:51:59,770 INFO    MainThread:12193 [wandb_init.py:_log_setup():533] Logging user logs to /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/run-20250312_235159-2g4rn5b5/logs/debug.log
2025-03-12 23:51:59,770 INFO    MainThread:12193 [wandb_init.py:_log_setup():534] Logging internal logs to /mnt/c/Users/ihkoo/programming/CRLQAS/jax_noisy/wandb/run-20250312_235159-2g4rn5b5/logs/debug-internal.log
2025-03-12 23:51:59,770 INFO    MainThread:12193 [wandb_init.py:init():619] calling init triggers
2025-03-12 23:51:59,770 INFO    MainThread:12193 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'general': {'episodes': 15000}, 'env': {'num_qubits': 4, 'num_layers': 40, 'err_mitig': 0.0, 'rand_halt': 1.0, 'n_shots': 0.0, 'noise_models': '[depolarizing, two_depolarizing]', 'noise_values': [0.000522, 0.0125], 'fake_min_energy': -1.99009719, 'fn_type': 'incremental_with_fixed_ends', 'accept_err': 1.0160872, 'shift_threshold_time': 500, 'shift_threshold_ball': 0.0005, 'success_thresh': 25, 'succ_radius_shift': 10, 'succes_switch': 1.0160872, 'thresholds': [], 'switch_episodes': [], 'curriculum_type': 'MovingThreshold'}, 'problem': {'ham_type': 'H2', 'geometry': 'H .0 .0 +.35; H .0 .0 -.35', 'taper': 1, 'mapping': 'jordan_wigner'}, 'agent': {'batch_size': 1000, 'memory_size': 20000, 'neurons': [1000, 1000, 1000, 1000, 1000], 'dropout': 0.0, 'learning_rate': 0.0003, 'angles': 0, 'en_state': 1, 'agent_type': 'DeepQNstep', 'agent_class': 'DQN_Nstep', 'n_step': 5, 'init_net': 0, 'update_target_net': 500, 'final_gamma': 0.005, 'epsilon_decay': 0.99995, 'epsilon_min': 0.05, 'epsilon_restart': 1.0}, 'non_local_opt': {'global_iters': 100, 'method': 'scipy_each_step', 'optim_alg': 'COBYLA'}}
2025-03-12 23:51:59,770 INFO    MainThread:12193 [wandb_init.py:init():669] starting backend
2025-03-12 23:51:59,771 INFO    MainThread:12193 [wandb_init.py:init():673] sending inform_init request
2025-03-12 23:51:59,780 INFO    MainThread:12193 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-12 23:51:59,780 INFO    MainThread:12193 [wandb_init.py:init():686] backend started and connected
2025-03-12 23:51:59,802 INFO    MainThread:12193 [wandb_init.py:init():781] updated telemetry
2025-03-12 23:51:59,886 INFO    MainThread:12193 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-03-12 23:52:00,221 ERROR   MainThread:12193 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity ihkoo not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-03-12 23:52:00,221 ERROR   MainThread:12193 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/inae/miniconda3/envs/CRL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/home/inae/miniconda3/envs/CRL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity ihkoo not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-03-12 23:52:00,233 WARNING MsgRouterThr:12193 [router.py:message_loop():75] message_loop has been closed
